app/dao/knowledge_card_dao.py, app/models/__init__.py, app/models/knowledge_card_model.py, app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py, app/utils/__init__.py
28/03/2025
-Created a pydantic model KnowledgeCardRequest 
-Added a post router to knowledge_card_routes to add a knowledge card
-Updated services/knowledge_card_services to handle a new card 
-Updated dao/knowledge_card_dao to add new knowledge card data to DB
- New Functions Added, No Changes.
=> Created a feature to add a knowledge card

app/dao/knowledge_card_dao.py, app/models/__init__.py, app/models/knowledge_card_model.py, app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py
01/04/2025
- Added a function in dao/knowledge_card_dao to update card details(update note, summary of card)
- Created a pydantic model (EditKnowledgeCard)
- Added edit_knowledge_card route (put request) in routes/knowledge_card_routes
- Added function edit_knowledge_card in services/knowledge_card_services to handle the editing of a card.
- New functions added, no changes
=> added edit knowledge card feature

app/config.py, app/utils/sraper.py
Shaikh Moizuddin Arif
03/04/2025
Fixed the scrapping module's authentication route. As it was expired.
- Updated the config.py file and sraper.py file
- Locally Tested
- The Scraping endpoint url had expired which had to be updated
=> Fixed Scraper Module

start.sh
added start.sh script for deplyoment
=> start.sh Script

app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py, app/utils/__init__.py, app/utils/get_yt_transcript.py, app/utils/youtube_url_checker.py, requirements.txt
08/04/2025
- Created Utility function to get Transcript of YouTube video
- Created Utility function to check if URL provided by user is YouTube or any other URL.
-Updated knowledge_card_route.py to handle return message.
-Updated knowledge_card_services.py to process with YouTube URL.
-Updated requirements.txt file
- Local testing, testing with Swagger UI
=> updated the application to handle youtube url's

app/dao/knowledge_card_dao.py, app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py, app/utils/ai_gemini.py, app/utils/document_generator.py, app/utils/knowledge_card_helper.py, app/utils/thumbnails.py
10/04/2025
-added category generation function in utils/ai_gemini.py
-added toggle functions for favorites and archives in dao/knowledge_card_dao.py
- updated AI text processing to generate better summaries
- updated routes file to include favorite, archive routes
- updated document generator to export files with rich text
-  updated services/knowledge_card_services.py to handle new function.
- Local testing, swagger UI
=> added category feature, updated summary generation and thumbnails

app/dao/knowledge_card_dao.py, app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py
15/04/2025
- Created new route to fetch all public cards
- updated dao file, added a function to fetch all public cards 
=> added route to fetch public cards

app/dao/knowledge_card_dao.py, app/models/__init__.py, app/models/knowledge_card_model.py, app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py, app/utils/knowledge_card_helper.py
16/04/2025
- created a like/unlike functionality for a public card
- added liking/unliking function in knowledge_card_dao.py
- updated knowledge_card_model.py
- added new routes in knowledge_card_route.py
- updated knowledge_card_service.py to process the new functionality
- Local testing, swagger UI
=> Global card feature, number of likes on card, some enhancements

app/dao/knowledge_card_dao.py, app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py
18/04/2025
Added Pagination Functionality
-         modified:   app/dao/knowledge_card_dao.py
-         modified:   app/routes/knowledge_card_routes.py
-         modified:   app/services/knowledge_card_service.py 
- Locally Tested
=> Added Pagination Functionality

app/services/knowledge_card_service.py, app/utils/document_generator.py, requirements.txt
23/04/2025
Added new fields to the pdf, q&a and knowledge map (if the knowledge card contains these fields)
- modified:   knowledge_card_dao.py
- downloaded and tested the file content
=> Added q&a and Knowledge map fields to pdf generation

app/models/knowledge_card_model.py, app/services/knowledge_card_service.py
24/04/2025
- saving source URL field value correctly, so that front end view of shared card can show source URL appropriately.
=> shared card feature bug fixes

app/dao/category_dao.py, app/migrate_existing_categories.py, app/routes/knowledge_card_routes.py, app/services/__init__.py, app/services/category_services.py, app/services/knowledge_card_service.py
28/04/2025
- Created category_dao.py 
- Created two helper files for 
1. migrating categories from card data to category collection
2. changing data structure of category of card to an array from string.
- Added a new route to fetch all categories
- Created category_services.py for handling category related services
- Updated knowledge_card_services.py to dandle category related changes
- Updated route file to handle new category data structure
=> added a feature to customise category of a card

app/dao/knowledge_card_dao.py, app/models/__init__.py, app/models/knowledge_card_model.py, app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py
28/04/2025
- Created new route in knowledge card routes file to handle add tag call
- Created new function add_tag in knowledge card services to handle add tag call
- Created new function update_tag in knowledge card services to handle add tag call
=> add tag functionality

app/services/knowledge_card_service.py
28/04/2025
Bug fixes in knowledge card services (process new knowledge card)
=> bug fixing in add knowledge card

app/dao/knowledge_card_dao.py, app/models/knowledge_card_model.py, app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py
03/05/2025
Added custom category features and bug fixes for category data type
- modified:   routes/knowledge_card_routes.py
- modified:   services/knowledge_card_service.py
- Locally Tested
=> Bug fix/custom category data type

app/models/__init__.py, app/models/knowledge_card_model.py, app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py, app/utils/ai_gemini.py
07/05/2025
- Added new model to answer custom questions on the basis of content of knowledge card
- Added new pydantic request model.
- Added new route, and new function in services to handle the functionality
=> chatbot feature inside a knowledge card

app/__init__.py, app/dao/card_cluster_dao.py, app/dao/category_dao.py, app/dao/knowledge_card_dao.py, app/dao/user_dao.py, app/database/connection.py, app/main.py, app/migrate_existing_categories.py, app/routes/auth_routes.py, app/routes/card_cluster_routes.py, app/routes/knowledge_card_routes.py, app/script_to_change_structure.py, app/services/auth_service.py, app/services/card_cluster_service.py, app/services/category_services.py, app/services/knowledge_card_service.py, app/utils/ai_gemini.py, app/utils/clustering_module.py, app/utils/embedder.py, app/utils/jwt_handler.py, app/utils/knowledge_card_helper.py, app/utils/sraper.py, app/utils/topic_name_generator.py, fix_imports.py
08/05/2025
fixed imports e.g.,
---> from utils import ...
to ---> from app.utils import ...
-         modified:   app/__init__.py
-         modified:   app/dao/card_cluster_dao.py
-         modified:   app/dao/category_dao.py
-         modified:   app/dao/knowledge_card_dao.py
-         modified:   app/dao/user_dao.py
-         modified:   app/database/connection.py
-         modified:   app/main.py
-         modified:   app/migrate_existing_categories.py
-         modified:   app/routes/auth_routes.py
-         modified:   app/routes/card_cluster_routes.py
-         modified:   app/routes/knowledge_card_routes.py
-         modified:   app/script_to_change_structure.py
-         modified:   app/services/auth_service.py
-         modified: …
=> Fixed Imports of all files to Absolute imports

app/utils/ai_gemini.py
08/05/2025
Kaustubh Bhusane 
- Fine tunning the chatbot feature to answer custom question in more sophisticated manner
=> enhancing the custom prompt feature

start.sh
- Updated the starting script for deployment.
=> New start script

app/main.py
=> Changes for deployment

app/dao/category_dao.py, app/main.py, app/models/knowledge_card_model.py, app/routes/knowledge_card_routes.py, app/services/category_services.py, app/services/knowledge_card_service.py, app/utils/ai_gemini.py, requirements.txt, start.sh
09/05/2025
Fixed upload behaviour to raise error when file type is other than pdf and docx
- modified:   app/services/knowledge_card_service.py
- modified:   requirements.txt
- Locally tested
=> Fixed Uplolad File Behaviour for Invalid file type

app/dao/knowledge_card_dao.py, app/routes/knowledge_card_routes.py, app/services/knowledge_card_service.py, package-lock.json
11/05/2025
Created Dashboard APIs to send Statistics to Dashboards like numbers of Total Cards, Favourites, Archived, Bookmarked, Recent cards list
- Refactored `app/dao/knowledge_card_dao.py`, `app/routes/knowledge_card_routes.py`
- Locally Tested
=> Dahboard feature for user

app/config.py, app/services/knowledge_card_service.py, app/utils/ai_gemini.py, app/utils/get_yt_transcript.py
14/05/2025
- modified:   app/config.py
- modified:   app/services/knowledge_card_service.py
- modified:   app/utils/ai_gemini.py
- modified:   app/utils/get_yt_transcript.py
Testing 
Local testing, Unit testing 
- Optimized Category & Thumbnail Generation 
- Fixed test case - TC_ADD_KC_006 (YouTube Video Without Transcript or in languages other than English )
Now the Card creation process stops gracefully if the youtube link provided doesn't have transcript or it is in other languages 
than English)
=> defect fixing in Youtube Transcript, Optimizing Category and Thumbnail generation
